---
alias: areas_living_room_lights
description: >-
  Controls the lights in the living room.
mode: single
id: 7a380dca-204f-4d64-bf36-3591919a1abd
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.home_presence

  - platform: state
    entity_id:
      - input_select.light_schedule

variables:
  anchors:
    - &turn_off_lights
      alias: "Turn the lights off"
      service: light.turn_off
      target:
        area_id: living_room

    - &turn_off_switches
      alias: "Turn the lights off"
      service: switch.turn_off
      target:
        area_id: living_room

    - &turn_on_lights_against_thieves
      alias: "Turn the dressoir light on"
      service: switch.turn_on
      target:
        entity_id:
          - scene.living_room_away

    - &turn_on_cosy_evening_lights
      alias: "Make it a cosy evening"
      service: scene.turn_on
      target:
        entity_id: scene.living_room_cosy

action:
  - choose:
      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.home_presence
                state: "on"
              - condition: state
                entity_id: input_select.light_schedule
                state: "evening"
        sequence:
          - *turn_on_cosy_evening_lights

      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.home_presence
                state: "off"
              - condition: state
                entity_id: input_select.light_schedule
                state: "evening"
        sequence:
          - *turn_on_lights_against_thieves

      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.home_presence
                state: "off"
              - condition: state
                entity_id: input_select.light_schedule
                state: "night"
        sequence:
          - *turn_off_lights
          - *turn_off_switches

      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.home_presence
                state: "off"
              - condition: state
                entity_id: input_select.light_schedule
                state: "evening"
        sequence:
          - *turn_on_lights_against_thieves
