---
description: >
  Automatically select the light schedule that suits the situation
  or time of day
alias: house_light_schedule
id: 62ee2d9b-9144-4309-9831-ec7e19d9fbfb
mode: single
trace:
  stored_traces: 25

trigger:
  - platform: state
    entity_id:
      - binary_sensor.home_presence

  - platform: numeric_state
    above: 150
    entity_id:
      - sensor.outside_light_intensity

  - platform: numeric_state
    below: 150
    entity_id:
      - sensor.outside_light_intensity

  - platform: time
    at: "08:00:00"

  - platform: time
    at: "08:30:00"

  - platform: time
    at: "09:30:00"

  - platform: time
    at: "21:30:00"

  - platform: time
    at: "22:30:00"

  - platform: homeassistant
    event: start

variables:
  anchors:
    - &select_schedule
      alias: "Select the schedule"
      service: input_select.select_option
      target:
        entity_id: input_select.light_schedule

action:
  - choose:
      - conditions:
          - condition: time
            after: "22:30:00"
            before: "07:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "night"

      - conditions:
          - or:
            - and:
                - condition: numeric_state
                  entity_id: sensor.outside_light_intensity
                  below: 150
                - condition: time
                  after: "17:30:00"
                  before: "07:00:00"
            - condition: time
              after: "21:30:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "evening"

    default:
      - <<: *select_schedule
        data:
          option: "day"
