---
trigger:
  platform: time_pattern
  minutes: "/1"
sensor:
  - name: weatherman_data
    state: "OK"
    attributes:
      weather_condition_now: >
        {% set cond_now = states.weather.openweathermap.state %}
        {% if states('sun.sun') == 'below_horizon' %}
            {% if cond_now == 'sunny' %} night {% elif cond_now == 'partlycloudy' %} night-partly-cloudy {% else %} {{ cond_now }} {% endif %}
        {% else %}
            {{ cond_now }}
        {% endif %}

      weather_condition: >
        {% set cond0 = states.sensor.openweathermap_condition.state %}
        {{ cond0 }}
      weather_temperature: >
        {{ states.sensor.openweathermap_temperature.state | round }}
